package:
  name: tox
  version: "2.1.1"

source:
  fn: tox-2.1.1.tar.gz
  url: https://pypi.python.org/packages/source/t/tox/tox-2.1.1.tar.gz
  md5: fc5b38cce701ced90a89b9da24af1769

build:
  entry_points:
    - tox=tox:cmdline
    - tox-quickstart=tox._quickstart:main

requirements:
  build:
    - python
    - setuptools
    - virtualenv >=1.11.2
    - py >=1.4.17
    - pluggy >=0.3.0,<0.4.0

  run:
    - python
    - virtualenv >=1.11.2
    - py >=1.4.17
    - pluggy >=0.3.0,<0.4.0

test:
  imports:
    - tox

  requires:
    - tox

about:
  home: http://tox.testrun.org/
  license: MIT License
  summary: 'virtualenv-based automation of test activities'
