package:
  name: fastavro
  version: "0.8.5"

source:
  fn: fastavro-0.8.5.tar.gz
  url: https://pypi.python.org/packages/source/f/fastavro/fastavro-0.8.5.tar.gz
  md5: 5c51b9c92423c1579b63adf61478427b

build:
  entry_points:
    - fastavro = fastavro.__main__:main

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - fastavro

  commands:
    - fastavro --help

  requires:
    - flake8
    - nose

about:
  home: https://github.com/tebeka/fastavro
  license: MIT License
  summary: 'Fast iteration of AVRO files'
