# File : .pep8speaks.yml

scanner:
    diff_only: True  # If True, errors caused by only the patch are shown
    linter: flake8
no_blank_comment: True
message:
  updated:  # Messages when a PR is updated
      header: "Foo"
      footer: "Bar"
  no_errors: "There are currently no linting issues detected in this pull request. Cheers! :beers: "
only_mention_files_with_errors: False
