---
extends: default

ignore:
  - docs/_publish.yml

rules:
  document-start: disable
  line-length: disable # we already enforce this with prettier
  truthy: disable
  comments:
    min-spaces-from-content: 1
