codecov:
  notify:
    # a high number to try to delay codecov reporting until most of the test
    # runs have finished. Should match with comment.after_n_builds below.
    after_n_builds: 32

comment:
  after_n_builds: 32
  layout: "reach, diff, files"
  behavior: default
  require_changes: true # if true: only post the comment if coverage changes
  require_base: false # [yes :: must have a base report to post]
  require_head: true # [yes :: must have a head report to post]
  branches: null

ignore:
  - "docs/**"

coverage:
  status:
    project:
      default:
        # Allow for slight decreases in code coverage, makes
        # the coverage status checks a little less finicky
        threshold: 0.5%
        only_pulls: true
    patch:
      default:
        threshold: 0.5%
        only_pulls: true
