require_https = true
exclude = [
  "duckdb:/:memory",
  "postgres:/:*",
  "reference/selectors.md",
  "backends/impala.qmd",
  "raw_support_matrix.csv",
]
exclude_path = ["site/SUMMARY/index.html", "site/overrides/main.html"]
