# Automated Code and AI

::: {.callout-note}
The wording and general tone of this policy is taken from [FastAPI](https://fastapi.tiangolo.com/contributing/#automated-code-and-ai) and [pip-tools](https://github.com/jazzband/pip-tools/pull/2318/changes)
:::

You are encouraged to use all the tools you want to do your work and contribute
as efficiently as possible, this includes AI (LLM) tools, etc. Nevertheless,
contributions should have meaningful human intervention, judgement, context,
etc.

When interacting in Ibis spaces (issues, pull requests, Zulip, etc.), do not use
LLMs to speak for you, except for translation or grammar edits.  This includes
the creation of changelogs and PR descriptions.

Human-to-human communication is foundational to open source communities.

## Responsibility

Remember that you, not the LLM, are responsible for your contributions.

Be ready to discuss your changes.

Do not submit code you have not reviewed.

Do your best to follow the conventions and standards of the project.

Make sure your code really works.

Be thoughtful about testing and documentation.

Try to make your code brief, and recognize when less is more.

## Autonomous Code Submissions

The use of agents which write code and submit pull requests without human review
is not permitted.

## Closing Automated and AI PRs

If we see PRs that seem AI generated or automated in similar ways, we'll flag
them and close them.

The same applies to comments and descriptions, please don't copy paste the
content generated by an LLM.

## Human Effort Denial of Service

Using automated tools and AI to submit PRs or comments that we have to carefully
review and handle would be the equivalent of a Denial-of-service attack on our
human effort.

It would be very little effort from the person submitting the PR (an LLM prompt)
that generates a large amount of effort on our side (carefully reviewing code).

Please don't do that.

We'll need to block accounts that spam us with repeated automated PRs or comments.
