You can install Ibis and a supported backend with `pip`, `conda`, `mamba`, or `pixi`.

::: {.panel-tabset}

## Using `pip`

::: {.panel-tabset}

## BigQuery

Install with the BigQuery extra:

```{.bash}
pip install 'ibis-framework[bigquery]'
```

And connect:

```{.python}
import ibis

con = ibis.bigquery.connect()  # <1>
```

1. Adjust connection parameters as needed.

## Clickhouse

Install with the Clickhouse extra:

```{.bash}
pip install 'ibis-framework[clickhouse]'
```

And connect:

```{.python}
import ibis

con = ibis.clickhouse.connect()  # <1>
```

1. Adjust connection parameters as needed.

## Dask

Install with the Dask extra:

```{.bash}
pip install 'ibis-framework[dask]'
```

And connect:

```{.python}
import ibis

con = ibis.dask.connect()  # <1>
```

1. Adjust connection parameters as needed.

## DataFusion

Install with the DataFusion extra:

```{.bash}
pip install 'ibis-framework[datafusion]'
```

And connect:

```{.python}
import ibis

con = ibis.datafusion.connect()  # <1>
```

1. Adjust connection parameters as needed.

## Druid

Install with the Druid extra:

```{.bash}
pip install 'ibis-framework[druid]'
```

And connect:

```{.python}
import ibis

con = ibis.druid.connect()  # <1>
```

1. Adjust connection parameters as needed.

## DuckDB

Install with the DuckDB extra:

```{.bash}
pip install 'ibis-framework[duckdb]'
```

And connect:

```{.python}
import ibis

con = ibis.duckdb.connect()  # <1>
```

1. Adjust connection parameters as needed.

## Impala

Install with the Impala extra:

```{.bash}
pip install 'ibis-framework[impala]'
```

And connect:

```{.python}
import ibis
    
con = ibis.impala.connect()  # <1>
```

1. Adjust connection parameters as needed.

## MSSQL

Install with the MSSQL extra:

```{.bash}
pip install 'ibis-framework[mssql]'
```

And connect:

```{.python}
import ibis

con = ibis.mssql.connect()  # <1>
```

1. Adjust connection parameters as needed.

## MySQL

Install with the MySQL extra:

```{.bash}
pip install 'ibis-framework[mysql]'
```

And connect:

```{.python}
import ibis

con = ibis.mysql.connect()  # <1>
```

1. Adjust connection parameters as needed.
    
## Oracle

Install with the Oracle extra:

```{.bash}
pip install 'ibis-framework[oracle]'
```

And connect:

```{.python}
import ibis

con = ibis.oracle.connect()  # <1>
```

1. Adjust connection parameters as needed.
 
## pandas

Install with the pandas extra:

```{.bash}
pip install 'ibis-framework[pandas]'
```

And connect:

```{.python}
import ibis

con = ibis.pandas.connect()  # <1>
```

1. Adjust connection parameters as needed.
 
## Polars

Install with the Polars extra:

```{.bash}
pip install 'ibis-framework[polars]'
```

And connect:

```{.python}
import ibis

con = ibis.polars.connect()  # <1>
```

1. Adjust connection parameters as needed.
 
## PostgreSQL

Install with the Postgres extra:

```{.bash}
pip install 'ibis-framework[postgres]'
```

And connect:


```{.python}
import ibis

con = ibis.postgres.connect()  # <1>
```

1. Adjust connection parameters as needed.
 
## PySpark

Install with the PySpark extra:

```{.bash}
pip install 'ibis-framework[pyspark]'
```

And connect:


```{.python}
import ibis

con = ibis.pyspark.connect()  # <1>
```

1. Adjust connection parameters as needed.
 
## Snowflake

Install with the Snowflake extra:

```{.bash}
pip install 'ibis-framework[snowflake]'
```

And connect:

```{.python}
import ibis

con = ibis.snowflake.connect()  # <1>
```

1. Adjust connection parameters as needed.
 
## SQLite

Install with the SQLite extra:

```{.bash}
pip install 'ibis-framework[sqlite]'
```

And connect:

```{.python}
import ibis

con = ibis.sqlite.connect()  # <1>
```

1. Adjust connection parameters as needed.
 
## Trino

Install with the Trino extra:

```{.bash}
pip install 'ibis-framework[trino]'
```

And connect:


```{.python}
import ibis

con = ibis.trino.connect()  # <1>
```

1. Adjust connection parameters as needed.

:::

{{< include /_callouts/pypi_warning.qmd >}}

## Using `conda`

::: {.panel-tabset}

## BigQuery

Install for BigQuery:

```{.bash}
conda install -c conda-forge ibis-bigquery
```

And connect:

```{.python}
import ibis

con = ibis.bigquery.connect()  # <1>
```

1. Adjust connection parameters as needed.

## Clickhouse

Install for Clickhouse:

```{.bash}
conda install -c conda-forge ibis-clickhouse
```

And connect:

```{.python}
import ibis

con = ibis.clickhouse.connect()  # <1>
```

1. Adjust connection parameters as needed.

## Dask

Install for Dask:

```{.bash}
conda install -c conda-forge ibis-dask
```

And connect:

```{.python}
import ibis

con = ibis.dask.connect()  # <1>
```

1. Adjust connection parameters as needed.

## DataFusion

Install for DataFusion:

```{.bash}
conda install -c conda-forge ibis-datafusion
```

And connect:

```{.python}
import ibis

con = ibis.datafusion.connect()  # <1>
```

1. Adjust connection parameters as needed.

## Druid

Install for Druid:

```{.bash}
conda install -c conda-forge ibis-druid
```

And connect:

```{.python}
import ibis

con = ibis.druid.connect()  # <1>
```

1. Adjust connection parameters as needed.

## DuckDB

Install for DuckDB:

```{.bash}
conda install -c conda-forge ibis-duckdb
```

And connect:

```{.python}
import ibis

con = ibis.duckdb.connect()  # <1>
```

1. Adjust connection parameters as needed.

## Impala

Install for Impala:

```{.bash}
conda install -c conda-forge ibis-impala
```

And connect:

```{.python}
import ibis
    
con = ibis.impala.connect()  # <1>
```

1. Adjust connection parameters as needed.

## MSSQL

Install for MSSQL:

```{.bash}
conda install -c conda-forge ibis-mssql
```

And connect:

```{.python}
import ibis

con = ibis.mssql.connect()  # <1>
```

1. Adjust connection parameters as needed.

## MySQL

Install for MySQL:

```{.bash}
conda install -c conda-forge ibis-mysql
```

And connect:

```{.python}
import ibis

con = ibis.mysql.connect()  # <1>
```

1. Adjust connection parameters as needed.
    
## Oracle

Install for Oracle:

```{.bash}
conda install -c conda-forge ibis-oracle
```

And connect:

```{.python}
import ibis

con = ibis.oracle.connect()  # <1>
```

1. Adjust connection parameters as needed.
 
## pandas

Install for pandas:

```{.bash}
conda install -c conda-forge ibis-pandas
```

And connect:

```{.python}
import ibis

con = ibis.pandas.connect()  # <1>
```

1. Adjust connection parameters as needed.
 
## Polars

Install for Polars:

```{.bash}
conda install -c conda-forge ibis-polars
```

And connect:

```{.python}
import ibis

con = ibis.polars.connect()  # <1>
```

1. Adjust connection parameters as needed.
 
## PostgreSQL

Install for Postgres:

```{.bash}
conda install -c conda-forge ibis-postgres
```

And connect:


```{.python}
import ibis

con = ibis.postgres.connect()  # <1>
```

1. Adjust connection parameters as needed.
 
## PySpark

Install for PySpark:

```{.bash}
conda install -c conda-forge ibis-pyspark
```

And connect:


```{.python}
import ibis

con = ibis.pyspark.connect()  # <1>
```

1. Adjust connection parameters as needed.
 
## Snowflake

Install for Snowflake:

```{.bash}
conda install -c conda-forge ibis-snowflake
```

And connect:

```{.python}
import ibis

con = ibis.snowflake.connect()  # <1>
```

1. Adjust connection parameters as needed.
 
## SQLite

Install for SQLite:

```{.bash}
conda install -c conda-forge ibis-sqlite
```

And connect:

```{.python}
import ibis

con = ibis.sqlite.connect()  # <1>
```

1. Adjust connection parameters as needed.
 
## Trino

Install for Trino:

```{.bash}
conda install -c conda-forge ibis-trino
```

And connect:


```{.python}
import ibis

con = ibis.trino.connect()  # <1>
```

1. Adjust connection parameters as needed.

:::

## Using `mamba`

::: {.panel-tabset}

## BigQuery

Install for BigQuery:

```{.bash}
mamba install -c conda-forge ibis-bigquery
```

And connect:

```{.python}
import ibis

con = ibis.bigquery.connect()  # <1>
```

1. Adjust connection parameters as needed.

## Clickhouse

Install for Clickhouse:

```{.bash}
mamba install -c conda-forge ibis-clickhouse
```

And connect:

```{.python}
import ibis

con = ibis.clickhouse.connect()  # <1>
```

1. Adjust connection parameters as needed.

## Dask

Install for Dask:

```{.bash}
mamba install -c conda-forge ibis-dask
```

And connect:

```{.python}
import ibis

con = ibis.dask.connect()  # <1>
```

1. Adjust connection parameters as needed.

## DataFusion

Install for DataFusion:

```{.bash}
mamba install -c conda-forge ibis-datafusion
```

And connect:

```{.python}
import ibis

con = ibis.datafusion.connect()  # <1>
```

1. Adjust connection parameters as needed.

## Druid

Install for Druid:

```{.bash}
mamba install -c conda-forge ibis-druid
```

And connect:

```{.python}
import ibis

con = ibis.druid.connect()  # <1>
```

1. Adjust connection parameters as needed.

## DuckDB

Install for DuckDB:

```{.bash}
mamba install -c conda-forge ibis-duckdb
```

And connect:

```{.python}
import ibis

con = ibis.duckdb.connect()  # <1>
```

1. Adjust connection parameters as needed.

## Impala

Install for Impala:

```{.bash}
mamba install -c conda-forge ibis-impala
```

And connect:

```{.python}
import ibis
    
con = ibis.impala.connect()  # <1>
```

1. Adjust connection parameters as needed.

## MSSQL

Install for MSSQL:

```{.bash}
mamba install -c conda-forge ibis-mssql
```

And connect:

```{.python}
import ibis

con = ibis.mssql.connect()  # <1>
```

1. Adjust connection parameters as needed.

## MySQL

Install for MySQL:

```{.bash}
mamba install -c conda-forge ibis-mysql
```

And connect:

```{.python}
import ibis

con = ibis.mysql.connect()  # <1>
```

1. Adjust connection parameters as needed.
    
## Oracle

Install for Oracle:

```{.bash}
mamba install -c conda-forge ibis-oracle
```

And connect:

```{.python}
import ibis

con = ibis.oracle.connect()  # <1>
```

1. Adjust connection parameters as needed.
 
## pandas

Install for pandas:

```{.bash}
mamba install -c conda-forge ibis-pandas
```

And connect:

```{.python}
import ibis

con = ibis.pandas.connect()  # <1>
```

1. Adjust connection parameters as needed.
 
## Polars

Install for Polars:

```{.bash}
mamba install -c conda-forge ibis-polars
```

And connect:

```{.python}
import ibis

con = ibis.polars.connect()  # <1>
```

1. Adjust connection parameters as needed.
 
## PostgreSQL

Install for Postgres:

```{.bash}
mamba install -c conda-forge ibis-postgres
```

And connect:


```{.python}
import ibis

con = ibis.postgres.connect()  # <1>
```

1. Adjust connection parameters as needed.
 
## PySpark

Install for PySpark:

```{.bash}
mamba install -c conda-forge ibis-pyspark
```

And connect:


```{.python}
import ibis

con = ibis.pyspark.connect()  # <1>
```

1. Adjust connection parameters as needed.
 
## Snowflake

Install for Snowflake:

```{.bash}
mamba install -c conda-forge ibis-snowflake
```

And connect:

```{.python}
import ibis

con = ibis.snowflake.connect()  # <1>
```

1. Adjust connection parameters as needed.
 
## SQLite

Install for SQLite:

```{.bash}
mamba install -c conda-forge ibis-sqlite
```

And connect:

```{.python}
import ibis

con = ibis.sqlite.connect()  # <1>
```

1. Adjust connection parameters as needed.
 
## Trino

Install for Trino:

```{.bash}
mamba install -c conda-forge ibis-trino
```

And connect:


```{.python}
import ibis

con = ibis.trino.connect()  # <1>
```

1. Adjust connection parameters as needed.

:::

## Using `pixi`

::: {.panel-tabset}

## BigQuery

Install for BigQuery:

```{.bash}
pixi add ibis-bigquery
```

And connect:

```{.python}
import ibis

con = ibis.bigquery.connect()  # <1>
```

1. Adjust connection parameters as needed.

## Clickhouse

Install for Clickhouse:

```{.bash}
pixi add ibis-clickhouse
```

And connect:

```{.python}
import ibis

con = ibis.clickhouse.connect()  # <1>
```

1. Adjust connection parameters as needed.

## Dask

Install for Dask:

```{.bash}
pixi add ibis-dask
```

And connect:

```{.python}
import ibis

con = ibis.dask.connect()  # <1>
```

1. Adjust connection parameters as needed.

## DataFusion

Install for DataFusion:

```{.bash}
pixi add ibis-datafusion
```

And connect:

```{.python}
import ibis

con = ibis.datafusion.connect()  # <1>
```

1. Adjust connection parameters as needed.

## Druid

Install for Druid:

```{.bash}
pixi add ibis-druid
```

And connect:

```{.python}
import ibis

con = ibis.druid.connect()  # <1>
```

1. Adjust connection parameters as needed.

## DuckDB

Install for DuckDB:

```{.bash}
pixi add ibis-duckdb
```

And connect:

```{.python}
import ibis

con = ibis.duckdb.connect()  # <1>
```

1. Adjust connection parameters as needed.

## Impala

Install for Impala:

```{.bash}
pixi add ibis-impala
```

And connect:

```{.python}
import ibis
    
con = ibis.impala.connect()  # <1>
```

1. Adjust connection parameters as needed.

## MSSQL

Install for MSSQL:

```{.bash}
pixi add ibis-mssql
```

And connect:

```{.python}
import ibis

con = ibis.mssql.connect()  # <1>
```

1. Adjust connection parameters as needed.

## MySQL

Install for MySQL:

```{.bash}
pixi add ibis-mysql
```

And connect:

```{.python}
import ibis

con = ibis.mysql.connect()  # <1>
```

1. Adjust connection parameters as needed.
    
## Oracle

Install for Oracle:

```{.bash}
pixi add ibis-oracle
```

And connect:

```{.python}
import ibis

con = ibis.oracle.connect()  # <1>
```

1. Adjust connection parameters as needed.
 
## pandas

Install for pandas:

```{.bash}
pixi add ibis-pandas
```

And connect:

```{.python}
import ibis

con = ibis.pandas.connect()  # <1>
```

1. Adjust connection parameters as needed.
 
## Polars

Install for Polars:

```{.bash}
pixi add ibis-polars
```

And connect:

```{.python}
import ibis

con = ibis.polars.connect()  # <1>
```

1. Adjust connection parameters as needed.
 
## PostgreSQL

Install for Postgres:

```{.bash}
pixi add ibis-postgres
```

And connect:


```{.python}
import ibis

con = ibis.postgres.connect()  # <1>
```

1. Adjust connection parameters as needed.
 
## PySpark

Install for PySpark:

```{.bash}
pixi add ibis-pyspark
```

And connect:


```{.python}
import ibis

con = ibis.pyspark.connect()  # <1>
```

1. Adjust connection parameters as needed.
 
## Snowflake

Install for Snowflake:

```{.bash}
pixi add ibis-snowflake
```

And connect:

```{.python}
import ibis

con = ibis.snowflake.connect()  # <1>
```

1. Adjust connection parameters as needed.
 
## SQLite

Install for SQLite:

```{.bash}
pixi add ibis-sqlite
```

And connect:

```{.python}
import ibis

con = ibis.sqlite.connect()  # <1>
```

1. Adjust connection parameters as needed.
 
## Trino

Install for Trino:

```{.bash}
pixi add ibis-trino
```

And connect:


```{.python}
import ibis

con = ibis.trino.connect()  # <1>
```

1. Adjust connection parameters as needed.

:::

:::
