# Requirements and setup

In this tutorial, we will connect to Starburst Galaxy and verify our connection. Following tutorials will go through the basics of Ibis on Starburst Galaxy's demo data.

## Prerequisites

You need a Python environment with [Ibis installed](/install.qmd) and a [Starburst Galaxy account](https://www.starburst.io/platform/starburst-galaxy/start).

## Connect to Starburst Galaxy

First, connect to Starburst Galaxy. We'll use a `.env` in this  example for secrets that are loaded as environment variables. This requires installing the `python-dotenv` package -- alternatively, you can set the environment variables for your system.

::: {.callout-tip}
Hover over (or click on mobile) the numbers in the code blocks to see tips and explanations.
:::

```{python}
import os # <1>
import ibis # <1>
from dotenv import load_dotenv # <1>

ibis.options.interactive = True # <2>

load_dotenv() # <3>

user = os.getenv("USERNAME") # <4>
password = os.getenv("PASSWORD") # <4>
host = os.getenv("HOSTNAME") # <4>
port = os.getenv("PORTNUMBER") # <4>
catalog = "sample" # <5>
schema = "demo" # <5>

con = ibis.trino.connect( # <6>
    user=user, password=password, host=host, port=port, database=catalog, schema=schema # <6>
) # <6>
con # <7>
```

1. Import necessary libraries.
2. Use Ibis in interactive mode.
3. Load environment variables.
4. Load secrets from environment variables.
5. Use the sample demo data.
6. Connect to Starburst Galaxy.
7. Display the connection object.

## Verify connection

List the tables your connection has:

```{python}
con.list_tables()
```

Run a SQL query:

```{python}
con.sql("select 1 as a")
```

If you have any issues, check your connection details above. If you are still having issues, [open an issue on Ibis](https://github.com/ibis/ibis-project/issues/new/choose) and we'll do our best to help you!

## Next steps

Now that you're connected to Starburst Galaxy, you can [continue this tutorial to learn the basics of Ibis](1_basics.qmd) or query your own data. See the rest of the Ibis documentation or [Starburst Galaxy documentation](https://docs.starburst.io/starburst-galaxy). You can [open an issue](https://github.com/ibis-project/ibis/issues/new/choose) if you run into one!
