package:
  name: kerberos
  version: "1.1.1"

source:
  fn: kerberos-1.1.1.tar.gz
  url: https://pypi.python.org/packages/source/k/kerberos/kerberos-1.1.1.tar.gz
  md5: 09ff604748b8c32dc9698e714f32b8a5

requirements:
  build:
    - python

  run:
    - python

about:
  home: http://www.calendarserver.org/
  license: Apache Software License
  summary: 'Kerberos high-level interface'
