package:
  name: sasl
  version: "0.2.1"

source:
  fn: sasl-0.2.1.tar.gz
  url: https://pypi.python.org/packages/source/s/sasl/sasl-0.2.1.tar.gz
  md5: ca093d9a3d6f20b79b964a5e5add0202
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - sasl = sasl:main
    #
    # Would create an entry point called sasl that calls sasl.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - six

  run:
    - python
    - six

test:
  # Python imports
  imports:
    - sasl

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/toddlipcon/python-sasl
  license: UNKNOWN
  summary: 'Cyrus-SASL bindings for Python'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
