package:
  name: pluggy
  version: "0.3.0"

source:
  fn: pluggy-0.3.0.tar.gz
  url: https://pypi.python.org/packages/source/p/pluggy/pluggy-0.3.0.tar.gz
  md5: 7e9e718884cac045efe1400c7ad016b5

requirements:
  build:
    - python
    - setuptools

  run:
    - python

about:
  license: MIT License
  summary: 'plugin and hook calling mechanisms for python'
