name: Bug Report
description: File a bug report
title: "bug: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out a bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: What version of ibis are you using?
      placeholder: "Ex: 3.2.0"
    validations:
      required: true
  - type: textarea
    id: backends
    attributes:
      label: What backend(s) are you using, if any?
      placeholder: "Ex: DuckDB"
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output or tracebacks. This will be automatically formatted into code, so no need for backticks.
      render: "sh"
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/ibis-project/ibis/blob/master/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
