name: Feature request
description: Suggest an idea for Ibis.
title: "feat: "
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out a feature request!
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: If so, please describe the problem.
      placeholder: "I am frustrated by ..."
    validations:
      required: false
  - type: textarea
    id: motivation
    attributes:
      label: What is the motivation behind your request?
      description: Discuss the use case behind this feature request, and why it is needed.
      placeholder: "I'm trying to do ... because I need ..."
    validations:
      required: false
  - type: textarea
    id: request
    attributes:
      label: Describe the solution you'd like
      description: Also discuss any alternatives you may have considered if applicable.
      placeholder: "I'd like ..."
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: What version of ibis are you running?
      placeholder: "Ex: 3.2.0"
    validations:
      required: true
  - type: textarea
    id: backends
    attributes:
      label: What backend(s) are you using, if any?
      placeholder: "Ex: DuckDB"
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/ibis-project/ibis/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
