name: New backend request
description: Suggest a new backend for Ibis.
title: "feat: "
labels: ["feature", "new backend"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out a new backend request!
  - type: textarea
    id: backend
    attributes:
      label: Which new backend would you like to see in Ibis?
      description: Please provide relevant links and disclose your affiliation with the backend.
      placeholder: "I would like a new backend for ..."
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/ibis-project/ibis/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
