SELECT
  "x",
  "y"
FROM (
  SELECT
    "t1"."x",
    "t1"."y",
    AVG("t1"."x") OVER (ORDER BY NULL ASC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS _w
  FROM (
    SELECT
      "t0"."x",
      SUM("t0"."x") OVER (ORDER BY NULL ASC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS "y"
    FROM "t" "t0"
  ) "t1"
  WHERE
    "t1"."y" <= 37
) _t
WHERE
  _w IS NOT NULL