package:
  name: thrift_sasl
  version: "0.1.0"

source:
  fn: thrift_sasl-0.1.0.tar.gz
  url: https://pypi.python.org/packages/source/t/thrift_sasl/thrift_sasl-0.1.0.tar.gz
  md5: 0710ffa4ed33a657090a8305fd71ca1e

requirements:
  build:
    - python
    - setuptools
    - thrift
    - thriftpy

  run:
    - python
    - thrift
    - thriftpy

test:
  imports:
    - thrift_sasl

about:
  home: https://github.com/cloudera/thrift_sasl
  license: Apache License, Version 2.0
  summary: 'Thrift SASL Python module that implements SASL transports for Thrift (`TSaslClientTransport`).'
