name: ibis-dev-flink
channels:
  - conda-forge
dependencies:
  # runtime dependencies
  - python =3.10
  - atpublic >=2.3
  - bidict >=0.22.1
  - clickhouse-connect >=0.5.23
  - dask >=2022.9.1
  - datafusion >=0.6
  - db-dtypes >=0.3.0,<2
  - deltalake
  - duckdb-engine <1,>=0.1.8
  - filelock >=3.7.0,<4
  - fsspec >=2022.1.0
  - gcsfs
  - geopandas >=0.6
  - google-cloud-bigquery >=3,<4
  - google-cloud-bigquery-storage >=2,<3
  - impyla >=0.17
  - numpy >=1.15,<2
  - oracledb >=1.3.1
  - packaging >=21.3
  - pandas >=1.2.5,<2.2
  - parsy >=2
  - pins >=0.8.2
  - poetry-core >=1.0.0
  - poetry-dynamic-versioning >=0.18.0
  - polars >=0.20.17
  - psycopg2 >=2.8.4
  - pyarrow =11.0.0
  - pyarrow-tests
  - pyarrow-hotfix >=0.4
  - pydata-google-auth
  - pydruid >=0.6.5
  - pymysql >=1
  - pyspark >=3
  - python-dateutil >=2.8.2
  - python-duckdb >=0.8.1
  - python-graphviz >=0.16
  - pytz >=2022.7
  - regex >=2021.7.6
  - requests >=2
  - rich >=12.4.4
  - shapely>=2,<3
  - snowflake-connector-python >=3.0.2
  - sqlglot >=22.5,<23.1
  - toolz >=0.11
  - trino-python-client >=0.321
  # geospatial
  - leafmap >=0.29.6
  # streaming
  - kafka-python
  - openjdk <21
  # test dependencies
  - filelock >=3.7.0,<4
  - hypothesis >=6.58.0,<7
  - pytest >=8.0.2,<9
  - pytest-benchmark >=3.4.1,<5
  - pytest-clarity >=1.0.1,<2
  - pytest-cov >=3.0.0,<5
  - pytest-httpserver >=1.0.5,<2
  - pytest-mock >=3.6.1,<4
  - pytest-randomly >=3.10.1,<4
  - pytest-repeat >=0.9.1,<0.10
  - pytest-snapshot >=0.9.0,<1
  - pytest-xdist >=2.3.0,<4
  - requests >=2,<3
  # docs
  - quarto >=1.4
  - altair >=5.0.1
  - distributed >=2022.9.1
  - ipykernel >=6.25.1
  - itables >=1.6.3
  - jupyter-cache
  - nbclient >=0.8.0
  - plotly >=5.16.1
  - plotnine >=0.12.2
  - py-cpuinfo >=9
  - quartodoc >=0.6.1
  - seaborn
  # dev utilities
  - codespell >=2.2.6
  - ipython
  - poetry-plugin-export
  - pre-commit
  - prettier
  - pydeps >=1.12.7
  - pyinstrument
  - ruff >=0.1.8
  - taplo
  - tqdm >=4.66.1
  - just
  # needed for apache-flink >=1.18.0
  - py4j =0.10.9.7
  - pip
  - pip:
      - apache-flink >=1.19.0
