package:
  name: requests-kerberos
  version: "0.7.0"

source:
  fn: requests-kerberos-0.7.0.tar.gz
  url: https://pypi.python.org/packages/source/r/requests-kerberos/requests-kerberos-0.7.0.tar.gz
  md5: d7cde195a95536c83a2ffd8a7050be4c

requirements:
  build:
    - python
    - setuptools
    - requests >=1.1.0
    - kerberos ==1.1.1

  run:
    - python
    - requests >=1.1.0
    - kerberos ==1.1.1

test:
  imports:
    - requests_kerberos

  requires:
    - mock

about:
  home: https://github.com/requests/requests-kerberos
  license: UNKNOWN
  summary: 'A Kerberos authentication handler for python-requests'
