package:
  name: ibis-framework
  version: "0.4.0"

source:
  fn: ibis-framework-0.4.0.tar.gz
  url: https://pypi.python.org/packages/source/i/ibis-framework/ibis-framework-0.4.0.tar.gz
  md5: 87323b54e070a538912cbb8d8174854a

requirements:
  build:
    - python
    - setuptools
    - pytest
    - numpy >=1.7.0
    - pandas >=0.12.0
    - impyla >=0.10.0
    - psutil ==0.6.1
    - hdfs ==1.4.3
    - six

  run:
    - python
    - pytest
    - numpy >=1.7.0
    - pandas >=0.12.0
    - impyla >=0.10.0
    - psutil ==0.6.1
    - hdfs ==1.4.3
    - six

test:
  imports:
    - ibis
    - ibis.expr
    - ibis.expr.tests
    - ibis.hive
    - ibis.hive.tests
    - ibis.impala
    - ibis.impala.tests
    - ibis.spark
    - ibis.spark.tests
    - ibis.sql
    - ibis.sql.presto
    - ibis.sql.presto.tests
    - ibis.sql.redshift
    - ibis.sql.redshift.tests
    - ibis.sql.sqlite
    - ibis.sql.sqlite.tests
    - ibis.sql.tests
    - ibis.sql.vertica
    - ibis.sql.vertica.tests
    - ibis.tests

about:
  license: Apache License, Version 2.0
  summary: 'Productivity-centric Python Big Data Framework'
