package:
  name: ibis-framework
  version: "0.6.0"

source:
  fn: ibis-framework-v0.6.0.tar.gz
  url: https://pypi.python.org/packages/source/i/ibis-framework/ibis-framework-v0.6.0.tar.gz
  md5: 44972ecee06c75cbd2e86d0d96b02794

requirements:
  build:
    - python
    - setuptools
    - pytest
    - numpy >=1.7.0
    - pandas >=0.12.0
    - impyla >=0.12.0
    - hdfs >=2.0.0
    - sqlalchemy >=1.0.0
    - six
    - mock

  run:
    - python
    - pytest
    - numpy >=1.7.0
    - pandas >=0.12.0
    - impyla >=0.12.0
    - hdfs >=2.0.0
    - sqlalchemy >=1.0.0
    - six
    - mock

test:
  imports:
    - ibis
    - ibis.expr
    - ibis.expr.tests
    - ibis.hive
    - ibis.hive.tests
    - ibis.impala
    - ibis.impala.tests
    - ibis.spark
    - ibis.spark.tests
    - ibis.sql
    - ibis.sql.presto
    - ibis.sql.presto.tests
    - ibis.sql.redshift
    - ibis.sql.redshift.tests
    - ibis.sql.sqlite
    - ibis.sql.sqlite.tests
    - ibis.sql.tests
    - ibis.sql.vertica
    - ibis.sql.vertica.tests
    - ibis.tests

about:
  license: Apache License, Version 2.0
  summary: 'Productivity-centric Python Big Data Framework'
