package:
  name: ibis-framework
  version: {{ environ.get('GIT_DESCRIBE_TAG', '').replace('v', '')}}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}_0
  {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}

source:
  path: ../..

requirements:
  build:
    - numpy >=1.7.0
    - pandas >=0.12.0
    - python
    - setuptools
    - six
    - toolz
  run:
    - numpy >=1.7.0
    - pandas >=0.12.0
    - python
    - setuptools
    - six
    - toolz

test:
  requires:
    - mock
    - numpy >=1.7.0
    - pandas >=0.12.0
    - pytest <=2.9.2
    - python
    - six
    - toolz
  imports:
    - ibis
    - ibis.expr
    - ibis.expr.tests
    - ibis.hive
    - ibis.hive.tests
    - ibis.impala
    - ibis.impala.tests
    - ibis.spark
    - ibis.spark.tests
    - ibis.sql
    - ibis.sql.presto
    - ibis.sql.presto.tests
    - ibis.sql.redshift
    - ibis.sql.redshift.tests
    - ibis.sql.sqlite
    - ibis.sql.sqlite.tests
    - ibis.sql.tests
    - ibis.sql.vertica
    - ibis.sql.vertica.tests
    - ibis.tests
  commands:
    - py.test --tb=short --pyargs ibis

about:
  license: Apache License, Version 2.0
  summary: 'Productivity-centric Python Big Data Framework'
