package:
  name: hdfs
  version: "2.0.4"

source:
  fn: hdfs-2.0.4.tar.gz
  url: https://pypi.python.org/packages/source/h/hdfs/hdfs-2.0.4.tar.gz
  md5: c48b86a0fb05d22b5f4eb4cb84fc6452

build:
  entry_points:
    - hdfscli = hdfs.__main__:main
    # - hdfscli-avro = hdfs.ext.avro.__main__:main

requirements:
  build:
    - python
    - setuptools
    - docopt
    - requests >=2.7.0
    - six >=1.9.0

  run:
    - python
    - docopt
    - requests >=2.7.0
    - six >=1.9.0

test:
  imports:
    - hdfs
    - hdfs.ext
    # - hdfs.ext.avro

  commands:
    - hdfscli --help
    # - hdfscli-avro --help

about:
  home: http://hdfscli.readthedocs.org
  license: MIT License
  summary: 'HdfsCLI: API and command line interface for HDFS.'
