SELECT
  `t0`.`g`,
  SUM(`t0`.`f`) OVER (
    PARTITION BY `t0`.`g`
    ORDER BY NULL ASC
    ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING
  ) - SUM(`t0`.`f`) OVER (ORDER BY NULL ASC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS `result`
FROM `alltypes` AS `t0`