package:
  name: impyla
  version: "0.13.5"

source:
  path: ../../../impyla
build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}

requirements:
  build:
    - python
    - setuptools
    - six
    - bitarray
    - thrift
    - thriftpy >=0.3.5

  run:
    - python
    - setuptools
    - six
    - bitarray
    - thriftpy
    - thrift

test:
  imports:
    - impala
    - impala.tests
    - impala.thrift

about:
  home: https://github.com/cloudera/impyla
  license: Apache License, Version 2.0
  summary: 'Python client for the Impala distributed query engine'
