package:
  name: impyla
  version: "0.11.2"

source:
  git_url: https://github.com/cloudera/impyla

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}

requirements:
  build:
    - python
    - setuptools
    - six
    - thrift_sasl
    - bitarray
    - thrift
    - llvmpy
    - numba

  run:
    - python
    - setuptools
    - six
    - thrift_sasl
    - bitarray
    - thrift
    - llvmpy
    - numba

test:
  imports:
    - impala
    - impala._thrift_api
    - impala._thrift_gen
    - impala._thrift_gen.ExecStats
    - impala._thrift_gen.ImpalaService
    - impala._thrift_gen.Status
    - impala._thrift_gen.TCLIService
    - impala._thrift_gen.Types
    - impala._thrift_gen.beeswax
    - impala._thrift_gen.fb303
    - impala._thrift_gen.hive_metastore
    - impala.tests
    - impala.thrift
    # - impala.udf  # Test fails on osx-64

about:
  home: https://github.com/cloudera/impyla
  license: Apache License, Version 2.0
  summary: 'Python client for the Impala distributed query engine'
