package:
  name: impyla
  version: "0.12.0"

source:
  git_url: https://github.com/cloudera/impyla

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}

requirements:
  build:
    - python
    - setuptools
    - six
    - thrift_sasl
    - bitarray
    - thriftpy

  run:
    - python
    - setuptools
    - six
    - thrift_sasl
    - bitarray
    - thriftpy

test:
  imports:
    - impala
    - impala.tests
    - impala.thrift

about:
  home: https://github.com/cloudera/impyla
  license: Apache License, Version 2.0
  summary: 'Python client for the Impala distributed query engine'
