package:
  name: impyla
  version: "0.12.0"

source:
  fn: impyla-0.12.0.tar.gz
  url: https://pypi.python.org/packages/source/i/impyla/impyla-0.12.0.tar.gz
  md5: 80c0374ba450c171661eade087216611

build:
  preserve_egg_dir: True

requirements:
  build:
    - python
    - setuptools
    - six
    - thrift_sasl
    - bitarray
    - thriftpy

  run:
    - python
    - setuptools
    - six
    - thrift_sasl
    - bitarray
    - thriftpy

test:
  imports:
    - impala
    - impala.tests
    - impala.thrift

about:
  home: https://github.com/cloudera/impyla
  license: Apache License, Version 2.0
  summary: 'Python client for the Impala distributed query engine'
