FROM continuumio/miniconda3

RUN apt-get -qq update --yes \
 && apt-get -qq install --yes --no-install-recommends \
    build-essential git make clang libboost-dev postgresql-client ca-certificates \
 && rm -rf /var/lib/apt/lists/*

ARG PYTHON
ADD ci/requirements-dev.yml /

RUN conda config --add channels conda-forge \
 && conda update --all -y -q \
 && conda install -q -y \
        --file /requirements-dev.yml \
        python=$PYTHON \
 && conda clean --all -y

# TODO(kszucs): remove once the notes in requiremens-dev.yml is resolved
RUN pip install impyla>=0.14.2 pymapd>=0.8

COPY . /ibis
WORKDIR /ibis

RUN python setup.py develop
