FROM ibisproject/miniconda3

ARG python

ADD ci/requirements-dev-$python.yml /tmp/requirements-dev-$python.yml
RUN conda install -y --file "/tmp/requirements-dev-$python.yml"

ADD . /ibis
WORKDIR /ibis
