package:
  name: thrift
  version: "0.9.3"

source:
  fn: thrift-0.9.3.tar.gz
  url: https://pypi.python.org/packages/source/t/thrift/thrift-0.9.3.tar.gz
  md5: b519551d7a086bb0b4f222a8f566b7e8

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - thrift
    - thrift.protocol
    - thrift.server
    - thrift.transport

about:
  home: http://thrift.apache.org
  license: Apache License 2.0
  summary: 'Python bindings for the Apache Thrift RPC system'
