---
hide:
  - toc
---

# Operation support matrix

We provide Ibis's operation support matrix as a [Streamlit](https://streamlit.io/) app that shows supported operations for each backend. Ibis defines a common API for analytics and data transformation code that is transpiled to native code for each backend. This code is often, but not always, SQL -- see the [backends concept page](/concepts/backend.qmd) for details. Due to differences in SQL dialects and support for different operations in different backends, support for the full breadth of the Ibis API varies.

You can use this page to see which operations are supported on each backend.

::: {.callout-tip}
Backends with low coverage are good places to start contributing!

Each backend implements operations differently, but this is usually very similar to other backends. If you want to start contributing to ibis, it's a good idea to start by adding missing operations to backends that have low operation coverage.
:::

<div class="streamlit-app">
  <iframe class="streamlit-app-inner" width=760 height=600 src="https://ibis-project.streamlit.app/?embedded=true"></iframe>
</div>

::: {.callout-note}
This app is built using [`streamlit`](https://streamlit.io/).

You can develop the app locally by editing `docs/backends/app/backend_info_app.py` and opening a PR with your changes.

Test your changes locally by running

```sh
$ streamlit run docs/backends/app/backend_info_app.py
```

The changes will show up in the dev docs when your PR is merged!
:::

## Raw Data

```{python}
#| echo: false
!python ../gen_matrix.py
```

You can also download data from the above tables in [CSV format](./backends/raw_support_matrix.csv).

The code used to generate the linked CSV file is below.

```{python}
#| echo: false
#| output: asis
with open("../gen_matrix.py", mode="r") as f:
    print(f"```python\n{f.read()}\n```")
```
