package:
  name: avro
  version: "1.7.7"

source:
  fn: avro-1.7.7.tar.gz
  url: https://pypi.python.org/packages/source/a/avro/avro-1.7.7.tar.gz
  md5: e21ae1dffea4c96ff151ce35ca5a8875

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - avro

about:
  home: http://hadoop.apache.org/avro
  license: Apache License 2.0
  summary: 'Avro is a serialization and RPC framework.'
