name: Rotate bot keys
on:
  schedule:
    # https://crontab.guru/#0_0_1_*/3_*
    # "At 00:00 on day-of-month 1 in every 3rd month."
    - cron: "0 0 1 */3 *"

jobs:
  rotate_private_key:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a GitHub token
        uses: tibdex/github-app-token@v2
        id: generate_token
        with:
          app_id: ${{ secrets.SQUAWK_BOT_APP_ID }}
          private_key: ${{ secrets.SQUAWK_BOT_APP_PRIVATE_KEY }}

      - name: checkout
        uses: actions/checkout@v4

      - name: create issue to rotate key
        uses: peter-evans/create-issue-from-file@v4
        with:
          token: ${{ steps.generate_token.outputs.token }}
          title: "chore: rotate ibis bot keys"
          content-filepath: .github/rotate-key-template.md
          labels: ci
          assignees: cpcloud,jreback
