# This job intentionally collides with the Backend job in `ibis-backends.yml`
# that would be skipped because the paths are ignored.  This is so the
# `Backends` job isn't stuck in "expected" forever when it should be skipped
name: Backends
on:
  push:
    paths:
      - "docs/**"
      - "mkdocs.yml"
      - "**/*.md"
    branches:
      - master
      - "*.x.x"
  pull_request:
    paths:
      - "docs/**"
      - "mkdocs.yml"
      - "**/*.md"
    branches:
      - master
      - "*.x.x"
jobs:
  backends:
    runs-on: ubuntu-latest
    steps:
      - run: echo "No build required"
