name: Test Report
on:
  workflow_run:
    workflows: ["Ibis", "Backends"]
    types:
      - completed
    branches-ignore:
      - master

concurrency: report

jobs:
  report:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: completed
          commit: ${{ github.event.workflow_run.head_sha }}
          path: artifacts

      - name: publish test report
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          commit: ${{ github.event.workflow_run.head_sha }}
          files: artifacts/**/junit.xml
