name: Update requirements.txt

on:
  pull_request:
    paths:
      - pyproject.toml
      - poetry.lock

jobs:
  generate_requirements_txt:
    # this can only run on pull requests made from branches in the main ibis
    # repository ano not forks, since the add-and-commit action requires the
    # ability to push commits to the PR branch
    #
    # this condition checks whether the PR is coming from a branch in the main
    # repo
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - name: Generate a GitHub token
        uses: tibdex/github-app-token@v1
        id: generate_token
        with:
          app_id: ${{ secrets.SQUAWK_BOT_APP_ID }}
          private_key: ${{ secrets.SQUAWK_BOT_APP_PRIVATE_KEY }}

      - name: checkout
        uses: actions/checkout@v3
        with:
          token: ${{ steps.generate_token.outputs.token }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: install nix
        uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: setup cachix
        uses: cachix/cachix-action@v10
        with:
          name: ibis
          extraPullNames: nix-community,poetry2nix

      - name: generate requirements.txt
        run: nix run -f nix poetry -- export --dev --extras all --without-hashes --no-ansi > requirements.txt

      - name: setup git credentials
        uses: OleksiyRudenko/gha-git-credentials@v2.1
        with:
          token: ${{ steps.generate_token.outputs.token }}
          global: true
          name: ibis-squawk-bot[bot]
          email: ibis-squawk-bot[bot]@users.noreply.github.com

      - name: commit requirements.txt and push to PR
        run: |
          set -euo pipefail

          git add requirements.txt

          if git commit -m 'chore(requirements.txt): regenerate'; then
            # pull in case another commit happened in the meantime
            #
            # `ours` is actually the *other* changeset, not the current branch, per
            # https://stackoverflow.com/a/3443225/564538
            git pull --rebase -s recursive -X ours
            git push
          fi
