# Uploads index to our Algolia Index
name: Upload Index
on:
  workflow_dispatch:
  repository_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  upload-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python_version: "3.10"
      - name: Install Algolia API Dependencies
        run: |
          python -m pip install --upgrade algoliasearch

      - name: Upload Index
        run: |
          python .github/workflows/upload-algolia.py
        env:
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }} # need to add api key to secrets
          ALGOLIA_APP_ID: FPF3DG0E1W
          ALGOLIA_INDEX: prod_IBIS
          QUARTO_INDEX_PATH: search.json
