from __future__ import annotations  # noqa: INP001

import json
import os
from urllib.request import urlopen

from algoliasearch.search_client import SearchClient

api_key = os.getenv("ALGOLIA_API_KEY")
app_id = os.getenv("ALGOLIA_APP_ID")
index_name = os.getenv("ALGOLIA_INDEX")
index_file = os.getenv("QUARTO_INDEX_PATH")

# Download the index generated by quarto from the ibis website
with urlopen("https://ibis-project.org/search.json") as response:
    with open(index_file, "wb") as f:
        f.write(response.read())

client = SearchClient.create(app_id, api_key)
index = client.init_index(index_name)

with open(index_file) as f:
    records = json.load(f)


# Commenting the following since it's failing due to having big records.
# algoliasearch.exceptions.RequestException: Record at the position 459
# objectID=reference/expression-tables.html#methods is too big size=224921/10000
# bytes.

# index.replace_all_objects(records)
